version: '3'
services:
  # ---------------------------------------------- #
  api:
    image: poolziee/nexusmeals-api:latest
    depends_on:
      - orders
      - users
      - rabbitmq
      - redis_sessions
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - API_PORT=${API_PORT}
      - TCP_ORDERS_HOST=${TCP_ORDERS_HOST}
      - TCP_ORDERS_PORT=${TCP_ORDERS_PORT}
      - TCP_USERS_HOST=${TCP_USERS_HOST}
      - TCP_USERS_PORT=${TCP_USERS_PORT}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RMQ_ORDERS_QUEUE=${RMQ_ORDERS_QUEUE}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_SESSIONS_PORT=${REDIS_SESSIONS_PORT}
      - REDIS_SESSIONS_HOST=${REDIS_SESSIONS_HOST}
  # ---------------------------------------------- #
  orders:
    image: poolziee/nexusmeals-orders:latest
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RMQ_ORDERS_QUEUE=${RMQ_ORDERS_QUEUE}
      - TCP_ORDERS_HOST=${TCP_ORDERS_HOST}
      - TCP_ORDERS_PORT=${TCP_ORDERS_PORT}
  # ---------------------------------------------- #
  users:
    image: poolziee/nexusmeals-users:latest
    depends_on:
      - rabbitmq
      - users-db
    ports:
      - '${TCP_USERS_PORT}:${TCP_USERS_PORT}'
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RMQ_USERS_QUEUE=${RMQ_USERS_QUEUE}
      - TCP_USERS_HOST=${TCP_USERS_HOST}
      - TCP_USERS_PORT=${TCP_USERS_PORT}
      - MYSQL_USERS_URI=${MYSQL_USERS_URI}

  users-db:
    image: mysql:5.7.20
    container_name: '${MYSQL_USERS_DB_NAME}'
    environment:
      - MYSQL_DATABASE=${MYSQL_USERS_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '7201:3306'
  # ---------------------------------------------- #
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 7300:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  # ---------------------------------------------- #
  redis_sessions:
    container_name: ${REDIS_SESSIONS_HOST}
    image: redis:latest
    ports:
      - ${REDIS_SESSIONS_PORT}:${REDIS_SESSIONS_PORT}
  # ---------------------------------------------- #
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ${RABBITMQ_HOST_NAME}
    hostname: ${RABBITMQ_HOST_NAME}
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
