version: '3'
services:
  # ---------------------------------------------- #
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:debug 0.0.0.0:9229
    depends_on:
      - orders
      - users
      - rabbitmq
      - redis_sessions
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${API_PORT}:${API_PORT}'
      - '9229:9229'
    environment:
      - API_PORT=${API_PORT}
      - TCP_ORDERS_HOST=${TCP_ORDERS_HOST}
      - TCP_ORDERS_PORT=${TCP_ORDERS_PORT}
      - TCP_USERS_HOST=${TCP_USERS_HOST}
      - TCP_USERS_PORT=${TCP_USERS_PORT}
      - TCP_INVENTORY_HOST=${TCP_INVENTORY_HOST}
      - TCP_INVENTORY_PORT=${TCP_INVENTORY_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_SESSIONS_PORT=${REDIS_SESSIONS_PORT}
      - REDIS_SESSIONS_HOST=${REDIS_SESSIONS_HOST}
  # ---------------------------------------------- #
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:debug 0.0.0.0:9230 orders
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${TCP_ORDERS_PORT}:${TCP_ORDERS_PORT}'
      - '9230:9230'
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RMQ_ORDERS_QUEUE=${RMQ_ORDERS_QUEUE}
      - RMQ_INVENTORY_QUEUE=${RMQ_INVENTORY_QUEUE}
      - TCP_ORDERS_HOST=${TCP_ORDERS_HOST}
      - TCP_ORDERS_PORT=${TCP_ORDERS_PORT}
      - ORDERS_DB_URI=${ORDERS_DB_URI}
      - ORDERS_DB_NAME=${ORDERS_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  orders-db:
    image: mongo:6.0
    container_name: '${ORDERS_DB_NAME}'
    environment:
      - MONGO_INITDB_DATABASE=${ORDERS_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MYSQL_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /var/lib/orders-db
    ports:
      - '27017:27017'
  # ---------------------------------------------- #
  inventory:
    build:
      context: .
      dockerfile: ./apps/inventory/Dockerfile
      target: development
    command: npm run start:debug 0.0.0.0:9231 inventory
    depends_on:
      - rabbitmq
      - inventory-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${TCP_INVENTORY_PORT}:${TCP_INVENTORY_PORT}'
      - '9231:9231'
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RMQ_INVENTORY_QUEUE=${RMQ_INVENTORY_QUEUE}
      - RMQ_ORDERS_QUEUE=${RMQ_ORDERS_QUEUE}
      - RMQ_USERS_QUEUE=${RMQ_USERS_QUEUE}
      - TCP_INVENTORY_HOST=${TCP_INVENTORY_HOST}
      - TCP_INVENTORY_PORT=${TCP_INVENTORY_PORT}
      - MYSQL_INVENTORY_URI=${MYSQL_INVENTORY_URI}

  inventory-db:
    image: mysql:5.7.20
    container_name: '${MYSQL_INVENTORY_DB_NAME}'
    environment:
      - MYSQL_DATABASE=${MYSQL_INVENTORY_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /var/lib/inventory-db
    ports:
      - '7201:3306'
  # ---------------------------------------------- #
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:debug 0.0.0.0:9232 users
    depends_on:
      - rabbitmq
      - users-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${TCP_USERS_PORT}:${TCP_USERS_PORT}'
      - '9232:9232'
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RMQ_USERS_QUEUE=${RMQ_USERS_QUEUE}
      - TCP_USERS_HOST=${TCP_USERS_HOST}
      - TCP_USERS_PORT=${TCP_USERS_PORT}
      - MYSQL_USERS_URI=${MYSQL_USERS_URI}

  users-db:
    image: mysql:5.7.20
    container_name: '${MYSQL_USERS_DB_NAME}'
    environment:
      - MYSQL_DATABASE=${MYSQL_USERS_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /var/lib/users-db
    ports:
      - '7202:3307'
  # ---------------------------------------------- #
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 7300:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  # ---------------------------------------------- #
  redis_sessions:
    container_name: ${REDIS_SESSIONS_HOST}
    image: redis:latest
    ports:
      - ${REDIS_SESSIONS_PORT}:${REDIS_SESSIONS_PORT}
  # ---------------------------------------------- #
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ${RABBITMQ_HOST_NAME}
    hostname: ${RABBITMQ_HOST_NAME}
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
