services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: production
    depends_on:
      - orders
      - rabbitmq
    ports:
      - '3000:3000'
    env_file:
      - .env

  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: production
    depends_on:
      - rabbitmq
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
