# users.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: users
          image: poolziee/nexusmeals-users:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          envFrom:
            - configMapRef:
                name: nex-config
          env:
            - name: TCP_USERS_HOST
              value: '0.0.0.0'
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  selector:
    app: users
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: users-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
