apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-db-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/inventory-db/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  ports:
    - port: 3306
  selector:
    app: inventory-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
spec:
  selector:
    matchLabels:
      app: inventory-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - image: mysql:5.7.20
          name: inventory-db
          env:
            # Use secret in real usage
            - name: MYSQL_DATABASE
              value: 'inventory-db'
            - name: MYSQL_USER
              value: 'admin'
            - name: MYSQL_PASSWORD
              value: 'admin'
            - name: MYSQL_ROOT_PASSWORD
              value: 'admin'
          ports:
            - containerPort: 3306
              name: inventory-db
          volumeMounts:
            - name: inventory-db-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
      volumes:
        - name: inventory-db-persistent-storage
          persistentVolumeClaim:
            claimName: inventory-db-pv-claim
