apiVersion: v1
kind: Service
metadata:
  name: orders-db
spec:
  ports:
    - port: 3305
  selector:
    app: orders-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
spec:
  selector:
    matchLabels:
      app: orders-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orders-db
    spec:
      containers:
        - image: mysql:5.7.20
          imagePullPolicy: IfNotPresent
          name: orders-db
          env:
            - name: MYSQL_DATABASE
              value: 'orders-db'
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: nex-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nex-config
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nex-config
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3305
              name: orders-db
          volumeMounts:
            - name: orders-db-ephemeral-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
      volumes:
        - name: orders-db-ephemeral-storage
          emptyDir: {}
