apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  ports:
    - port: 3307
  selector:
    app: users-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
spec:
  selector:
    matchLabels:
      app: users-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - image: mysql:5.7.20
          imagePullPolicy: IfNotPresent
          name: users-db
          env:
            - name: MYSQL_DATABASE
              value: 'users-db'
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: nex-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nex-config
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nex-config
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3307
              name: users-db
          volumeMounts:
            - name: users-db-ephemeral-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
      volumes:
        - name: users-db-ephemeral-storage
          emptyDir: {}
