apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: poolziee/nexusmeals-inventory:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          envFrom:
            - configMapRef:
                name: nex-config
          env:
            - name: TCP_INVENTORY_HOST
              value: '0.0.0.0'
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  selector:
    app: inventory
