apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: poolziee/nexusmeals-users:latest
          ports:
            - containerPort: 3003 # Port for internal TCP communications
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          envFrom:
            - configMapRef:
                name: nex-config
          env:
            - name: TCP_USERS_HOST
              value: '0.0.0.0'
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  selector:
    app: users
