name: push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # TODO: Databases, rmq, redis.
        include:
          - dockerfile: ./apps/api/Dockerfile
            image: poolziee/nexusmeals-api
          - dockerfile: ./apps/orders/Dockerfile
            image: poolziee/nexusmeals-orders
          - dockerfile: ./apps/users/Dockerfile
            image: poolziee/nexusmeals-users
          - dockerfile: ./apps/inventory/Dockerfile
            image: poolziee/nexusmeals-inventory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  load-test:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply nex config
        run: |
          echo "${{ secrets.NEXCONFIG }}" > nex-config.yml
          kubectl apply -f nex-config.yml

      - name: Start the cluster
        run: |
          echo "TODO: Start NexusMeals cluster."

      - name: Load test
        run: |
          echo "TODO: Start load tests."

      - name: Cleanup
        run: |
          echo "TODO: Cleanup nex-config."
          echo "TODO: Cleanup NexusMeals cluster."
