name: build-push-and-load-test

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./apps/api/Dockerfile
            image: poolziee/nexusmeals-api
          - dockerfile: ./apps/orders/Dockerfile
            image: poolziee/nexusmeals-orders
          - dockerfile: ./apps/users/Dockerfile
            image: poolziee/nexusmeals-users
          - dockerfile: ./apps/inventory/Dockerfile
            image: poolziee/nexusmeals-inventory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  start-cluster:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply nex config
        run: |
          echo "${{ secrets.NEXCONFIG }}" > nex-config.yml
          kubectl apply -f nex-config.yml

      - name: Start the cluster
        run: |
          kubectl apply -f k8s/ingress-qua.yml
          kubectl apply -f k8s/prod/ --recursive
          sleep 30s

      - name: Wait for pods to be ready
        run: |
          kubectl wait --for=condition=Ready pod --all --timeout=180s

      - name: Wait for services to be ready
        run: |
          echo "TODO: Apply health checks in manifests instead of sleeping."
          sleep 300s

  load-test:
    needs: start-cluster
    runs-on: self-hosted

    steps:
      - name: Run k6 test
        run: |
          k6 run tests/load-test.js

  cleanup:
    runs-on: self-hosted
    needs: load-test
    if: always()
    steps:
      - name: Cleanup
        run: |
          kubectl delete -f nex-config.yml
          kubectl delete -f k8s/ingress-qua.yml
          kubectl delete -f k8s/prod/ --recursive
          rm -r *
