name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy images to Kubernetes
        run: |
          echo "TODO: Deploy images with tag '${{ github.event.release.tag_name }}' to Kubernetes."
